version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # For prod/clustering remove this, but you will get:
      #   max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
      # So put vm.max_map_count=262144 in /etc/sysctl.conf and sysctl -w vm.max_map_count=262144
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
